name = "tafsir-kurd"
compatibility_date = "2024-01-01"
pages_build_output_dir = "src"

[[kv_namespaces]]
binding = "ADMIN_KV"
id = "398995d1041042b498189d180b883513"

[env.production]
name = "tafsir-kurd"
