bs=chr(92)
sq=chr(39)
dq=chr(34)
lines=[]
def L(s): lines.append(s)
L(sq+"use strict"+sq+";")
L("")
L("const fs = require("+sq+"fs"+sq+");")
L("const path = require("+sq+"path"+sq+");")
L("")
L("const SRC_DIR  = "+sq+"C:/TafsirKurd/src"+sq+";")
L("const APP_JS   = "+sq+"C:/TafsirKurd/src/app/app.js"+sq+";")
L("const OUT_FILE = "+sq+"C:/TafsirKurd/scripts/scan-results.json"+sq+";")
L("const KURDISH_RE = /["+bs+"u0600-"+bs+"u06FF]/g;")
L("const MIN_KURDISH = 2;")
L("")
L("function countKurdish(str){const m=str.match(KURDISH_RE);return m?m.length:0;}")
L("function hasKurdish(str){return countKurdish(str)>=MIN_KURDISH;}")
L("function isPureNums(str){return /^["+bs+"u0660-"+bs+"u0669"+bs+"s]+/.test(str);}")
L("")

L("function getPage(fp){")
L("  fp=fp.replace(/"+bs*2+"/g,"+sq+"/"+sq+");")
L("  if(fp.includes("+sq+"/app/index.html"+sq+"))return "+sq+"android"+sq+";")
L("  const b=path.basename(fp,"+sq+".html"+sq+");")
L("  return b==="+sq+"index"+sq+"?"+sq+"index"+sq+":b;")
L("}")
L("")